tidelift: nuget/paratika-nopcommerce
patreon: sercanboyraz
open_collective: sercan-boyraz
ko_fi: sercanboyraz
otechie: sercanboyraz
custom: ["https://tr.linkedin.com/in/sercan-boyraz-a40429b7","https://blockchain.com/btc/payment_request?address=1DXLMdkm26G3cymcWYrTj6oHQtpFuEgJQG&amount=0.07570022&message=Donate 500 EUR","https://blockchain.com/btc/payment_request?address=1BVscT35BwGPFPAzz68tGkMhU4MUpiEcMD&amount=1&message=Donate Paratika NopCommerce",  "blockchain_wallet_198eDB1Hv6huEKPpGh3vKd5x1kMrYVWj88"]
